export const surpriseMePrompts = [
  "an armchair in the shape of an avocado",
  "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
  "teddy bears shopping for groceries in Japan, ukiyo-e",
  "an oil painting by Matisse of a humanoid robot playing chess",
  "panda mad scientist mixing sparkling chemicals, digital art",
  "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
  "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
  "an astronaut lounging in a tropical resort in space, vaporwave",
  "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
  "a stained glass window depicting a hamburger and french fries",
  "a pencil and watercolor drawing of a bright city in the future with flying cars",
  "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
  "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
  '"a sea otter with a pearl earring" by Johannes Vermeer',
  "an oil pastel drawing of an annoyed cat in a spaceship",
  "a painting of a fox in the style of Starry Night",
  "a bowl of soup that looks like a monster, knitted out of wool",
  "A plush toy robot sitting against a yellow wall",
  "A synthwave style sunset above the reflecting water of the sea, digital art",
  "Two futuristic towers with a skybridge covered in lush foliage, digital art",
  "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
  "A comic book cover of a superhero wearing headphones",
  "A centered explosion of colorful powder on a black background",
  "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
  "A photo of a white fur monster standing in a purple room",
  "A photo of Michelangelo's sculpture of David wearing headphones djing",
  "A Samurai riding a Horse on Mars, lomography.",
  "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
  "A realistic photograph of a young woman with blue eyes and blonde hair",
  "A man standing in front of a stargate to another dimension",
  "Spongebob Squarepants in the Blair Witch Project",
  "A velociraptor working at a hotdog stand, lomography",
  "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
  "A BBQ that is alive, in the style of a Pixar animated movie",
  "A futuristic cyborg dance club, neon lights",
  "The long-lost Star Wars 1990 Japanese Anime",
  "A hamburger in the shape of a Rubik’s cube, professional food photography",
  "A Synthwave Hedgehog, Blade Runner Cyberpunk",
  "Generate an image of a modern kitchen with stainless steel appliances and marble countertops.",
  "Create an image of a magical forest with glowing mushrooms and a winding path.",
  "Generate an abstract image with a black and white color scheme and geometric shapes.",
  "Create an image of a serene lake surrounded by trees and mountains.",
  "Generate a realistic image of a dog playing in the snow.",
  "Create an image of a futuristic cityscape with flying cars and tall skyscrapers.",
  "Generate an image of a tropical rainforest with colorful birds and exotic flowers.",
  "Create an abstract image with a purple and pink color scheme and organic shapes.",
  "Generate a realistic image of a person surfing on a wave at sunset.",
  "Create an image of an underwater scene with coral reefs and tropical fish.",
  "An astronaut encountering an alien life form on a distant planet, photography",
  "A Dinosaur exploring Cape Town, photography",
  "A Man falling in Love with his Computer, digital art",
  "A photograph of a cyborg exploring Tokyo at night, lomography",
  "Dracula walking down the street of New York City in the 1920s, black and white photography",
  "Synthwave aeroplane",
  "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
  "A Space Shuttle flying above Cape Town, digital art",
  "Generate a picture of a futuristic city skyline at night.",
  "Create an image of a unicorn grazing in a field of flowers.",
  "Generate an abstract image with a blue and green color scheme.",
  "Create an image of a sunset over a mountain range.",
  "Generate a realistic image of a cat sitting on a windowsill.",
  "Create an image of a fantasy landscape with a castle and dragon.",
  "Generate an image of a beach with palm trees and a clear blue sky.",
  "Create an abstract image with a red and orange color scheme.",
  "Generate a realistic image of a person walking in the rain.",
  "Create an image of a space station orbiting a distant planet.",
  "A giant snail racing against a tiny hare on a giant checkerboard",
  "A robot bartender serving drinks to a group of aliens in a space-themed bar",
  "A tree made of candy canes in a snowy landscape",
  "A mermaid riding a giant seahorse in a coral reef",
  "A fire-breathing dragon playing a game of basketball",
  "A unicorn with butterfly wings resting on a rainbow",
  "A superhero flying over a city made of candy",
  "A group of penguins playing ice hockey on a frozen lake",
  "An underwater city filled with bioluminescent creatures",
  "A wizard riding a broomstick through a forest of giant mushrooms",
  "A giant squid attacking a submarine in the deep ocean",
  "A group of aliens playing a game of soccer with a planet as the ball",
  "A flock of birds forming a pattern in the sky that spells out a word",
  "A group of fairies having a tea party on a giant mushroom",
  "A flying saucer landing in the middle of a bustling city street",
  "A group of penguins playing ice hockey with an orange slice as the puck",
  "A garden of flowers made entirely of different types of pasta",
  "A portrait of a lion wearing a top hat and monocle, sitting at a desk and writing with a quill pen",
  "A sculpture of a dragon made entirely out of ice cream cones",
  "An owl wearing a graduation cap, sitting at a desk with a stack of books and a diploma",
  "A city skyline made of jelly beans",
  "A beach scene with sandcastle-shaped clouds and palm trees made of cotton candy",
  "A person holding a bouquet of balloons that are shaped like different animals",
  "A bookshelf filled with books that are made entirely out of ice",
  "A dragonfly made of stained glass",
  "A pair of headphones made out of flowers",
  "A giraffe wearing a bowtie and reading a newspaper",
  "A rocket ship made out of breakfast foods",
  "A landscape scene with mountains made out of books and a river made out of paint",
  "A portrait of a human with a body made out of neon lights",
  "A castle made out of candy canes",
  "A computer keyboard made out of plants",
  "A garden scene with flowers made out of recycled materials",
  "A treehouse made out of seashells",
  "A portrait of a famous artist made out of their own artwork",
  "a painting of a unicorn with rainbow-colored hair",
  "a photograph of a giant squid battling a sperm whale",
  "a sculpture of a dragon made entirely out of recycled materials",
  "an oil painting of a mystical forest with floating islands",
  "a digital art piece of a cyberpunk city with flying motorcycles",
  "a photograph of a sea turtle wearing a top hat",
  "a watercolor painting of a mermaid sitting on a rock in the ocean",
  "a 3D rendering of a treehouse that looks like a UFO",
  "a black and white photograph of a lone figure standing on a deserted beach",
  "a sketch of a unicorn riding a skateboard",
  "a digital art piece of a futuristic city with a giant robot in the background",
  "a painting of a lion with a majestic mane made of fire",
  "a photograph of a group of penguins sledding down a hill",
  "a sculpture of a griffin made out of wire",
  "an oil painting of a sunset over an alien planet",
  "a photograph of a rainbow-colored sandcastle on a beach",
  "a digital art piece of a cyborg holding a bouquet of flowers",
  "a painting of a wolf with glowing eyes in a dark forest",
  "a sketch of a panda flying a hot air balloon",
  "a watercolor painting of a fairy garden with tiny mushrooms and flowers",
  "a 3D rendering of a futuristic spaceship docked at a space station",
  "a black and white photograph of a city skyline during a thunderstorm",
  "a digital art piece of a robot playing a guitar in a neon-lit alleyway",
  "a painting of a phoenix rising from the ashes",
  "a photograph of a group of flamingos standing in a lake",
  "a sculpture of a giant squid made out of glass",
  "an oil painting of a dragon breathing fire on a castle",
  "a photograph of a colorful parrot perched on a branch",
  "a digital art piece of a cyborg walking through a dystopian wasteland",
  "a painting of a bear catching a fish in a river",
  "a sketch of a cat wearing a space suit and exploring the moon",
  "a watercolor painting of a magical garden with a rainbow-colored fountain",
  "a 3D rendering of a robot factory with conveyor belts and assembly lines",
  "a black and white photograph of a lone wolf howling at the moon",
  "a digital art piece of a futuristic city with flying cars and holographic billboards",
  "a painting of a stag with antlers made of crystals",
  "a photograph of a group of dolphins jumping out of the water",
  "a sculpture of a unicorn made out of driftwood",
  "an oil painting of a stormy sea with a lighthouse in the distance",
  "a photograph of a red panda eating bamboo",
  "a digital art piece of a cyborg riding a motorcycle through a post-apocalyptic wasteland",
  "a painting of a tiger with a coat made of stars",
  "a sketch of a fox wearing a top hat and monocle",
  "a watercolor painting of a garden with a rainbow-colored bridge",
  "a 3D rendering of a futuristic laboratory with glowing test tubes",
  "a black and white photograph of a city street at night with raindrops on the pavement",
  "a digital art piece of a robot astronaut exploring a distant planet",
  "a painting of an eagle soaring through the clouds",
  "a photograph of a school of fish swimming in a coral reef",
  "A butterfly made of stained glass in front of a sunset sky",
  "A mermaid lounging on a giant clam shell in the ocean",
  "A painting of a dragon in the style of Van Gogh's 'Starry Night'",
  "A portrait of a lion with a crown made of flowers",
  "A neon sign in the shape of a flamingo, against a tropical backdrop",
  "A photo of a hummingbird drinking nectar from a flower",
  "An underwater scene with a school of fish and a shipwreck",
  "A still life painting of a vase of flowers with a skull hidden in it",
  "A sculpture of a robot made entirely out of recycled materials",
  "A photo of a man walking through a field of sunflowers at sunset",
  "A 3D render of a futuristic car driving on a neon-lit road",
  "An oil painting of a landscape with a rainbow and a waterfall",
  "A surreal photo of a person standing in the clouds with a giant paper airplane",
  "A modern art sculpture of a tree made out of metal pipes",
  "A digital painting of a person with an umbrella in the rain",
  "A photo of a polar bear with its cub in the Arctic",
  "A painting of a flamingo in the style of Pablo Picasso",
  "A photo of a city skyline reflected in a river at night",
  "An abstract painting of a galaxy with swirling colors",
  "A 3D render of a futuristic city with flying cars and holographic billboards",
  "A photo of a person standing on a mountaintop with a foggy valley below",
  "A painting of a tiger with vibrant rainbow stripes",
  "A photo of a waterfall in a lush green forest",
  "A sculpture of a giant hand reaching out of the ground",
  "An oil painting of a moonlit forest with fireflies",
  "A photo of a person sitting on a cliff overlooking the ocean at sunset",
  "A digital art illustration of a person with a cybernetic arm",
  "A painting of a peacock with its feathers in a fan",
  "A photo of a person standing in front of a giant spiral staircase",
  "A sculpture of a dragon made entirely out of sand",
  "A photo of a person walking through a colorful field of flowers",
  "A digital art illustration of a person with wings made of feathers",
  "A painting of a lion with a galaxy mane",
  "A photo of a person standing on a mountain peak with clouds below",
  "An abstract painting of a city skyline at night",
  "A sculpture of a robot dog made entirely out of scrap metal",
  "A photo of a person standing in front of a giant redwood tree",
  "A painting of an elephant with a tree growing out of its back",
  "A photo of a person walking through a misty forest with rays of light shining through the trees",
  "A digital art illustration of a person with a glowing third eye",
  "A painting of a wolf with a mystical aura",
  "A photo of a person standing on a beach with a stormy sky",
  "A sculpture of a dragon made entirely out of ice",
  "A photo of a person standing in front of a giant cactus",
  "A painting of a bear with a dreamy expression",
  "An abstract painting of a stormy sea",
  "A digital art illustration of a person with a robotic exoskeleton",
  "A photo of a person standing on a frozen lake at sunrise",
  "A sculpture of a giant spider made entirely out of fire",
];
